### ISSUE TITLE
Server Error: emrapi.sqlSearch.activePatientsByLocation

### ISSUE THREAD

**Issue by brookingcharlie** [Bahmni/bahmni-vagrant#1]
When doing a vagrant up using 05bd8dd, I'm seeing "Server Error: emrapi.sqlSearch.activePatientsByLocation" when going to https://192.168.33.10/bahmni/clinical/.

I'm using an unmodified Vagrantfile and bahmni-team/bahmni version 0.78.5257.1.

Is this due to an incompatibility between the front- and back-end packages installed in the vagrant box?

From my browser's debug tools, I can see the request returning a 500 status is https://192.168.33.10/openmrs/ws/rest/v1/bahmnicore/sql?location_uuid=c5854fd7-3f12-11e4-adec-0800271c1b75&provider_uuid=c1c26908-3f10-11e4-adec-0800271c1b75&q=emrapi.sqlSearch.activePatientsByLocation&v=full. Full content of the response:

```
{
    "error": {
        "message": "No such query:emrapi.sqlSearch.activePatientsByLocation",
        "code": "org.bahmni.module.bahmnicore.service.impl.SqlSearchServiceImpl:46",
        "detail": "java.lang.RuntimeException: No such query:emrapi.sqlSearch.activePatientsByLocation\n\tat org.bahmni.module.bahmnicore.service.impl.SqlSearchServiceImpl.getSql(SqlSearchServiceImpl.java:46)\n\tat org.bahmni.module.bahmnicore.service.impl.SqlSearchServiceImpl.search(SqlSearchServiceImpl.java:29)\n\tat org.bahmni.module.bahmnicore.web.v1_0.controller.SqlSearchController.search(SqlSearchController.java:33)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\n\tat java.lang.reflect.Method.invoke(Unknown Source)\n\tat org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)\n\tat org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:440)\n\tat org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:428)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)\n\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:844)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:618)\n\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:725)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n\tat org.openmrs.module.web.filter.ForcePasswordChangeFilter.doFilter(ForcePasswordChangeFilter.java:61)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:72)\n\tat org.openmrs.web.filter.GZIPFilter.doFilterInternal(GZIPFilter.java:64)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:70)\n\tat org.openmrs.module.webservices.rest.web.filter.AuthorizationFilter.doFilter(AuthorizationFilter.java:108)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:70)\n\tat org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:73)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:70)\n\tat org.openmrs.module.web.filter.ModuleFilter.doFilter(ModuleFilter.java:54)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n\tat org.openmrs.web.filter.OpenmrsFilter.doFilterInternal(OpenmrsFilter.java:109)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n\tat org.springframework.orm.hibernate3.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:230)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n\tat org.openmrs.web.filter.StartupFilter.doFilter(StartupFilter.java:105)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n\tat org.openmrs.web.filter.StartupFilter.doFilter(StartupFilter.java:105)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n\tat org.openmrs.web.filter.StartupFilter.doFilter(StartupFilter.java:105)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n\tat org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:534)\n\tat org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1081)\n\tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)\n\tat org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\n\tat java.lang.Thread.run(Unknown Source)\n"
    }
}
```

**Comment by aj-jaswanth** [comment]
@brookingcharlie https://github.com/Bahmni/default-config/blob/b5d90ebd6fada51a4f1be08a23480d8f706d0bb0/openmrs/apps/clinical/extension.json#L109

It defines a queue in the clinical app. But, the corresponding sql query is not found in the openmrs global properties. This issue is fixed in the latest version.

**Comment by brookingcharlie** [comment]
So to fix this I'm guessing I need to do something like: build the latest 'bahmni-core' module, replace the module that comes default with the bahmni-team/bahmni box, and then restart tomcat?

Is this the step that I'm missing? https://bahmni.atlassian.net/wiki/display/BAH/Setting+up+Bahmni+Dev+Environment#SettingupBahmniDevEnvironment-DevelopingOpenMRSJavamodules

In general, if I build and install/symlink the latest openmrs-module-bahmniapps and bahmni-core, will this fix a box with incompatible packages on it?

Was this a problem with the build of the vagrant box on Atlas or did I stuff something up?

**Comment by aj-jaswanth** [comment]
The actual problem is the openmrs mysql db dump that is used doesn't have the global property defined. It has nothing to do with the omods.

To fix it, add a global property in 'advanced settings' of OpenMRS UI. That should fix the issue.

Global property details : 
Name : emrapi.sqlSearch.activePatientsByLocation

Value : `select distinct concat(pn.given_name," ", pn.family_name) as name,
pi.identifier as identifier,
concat("",p.uuid) as uuid,
concat("",v.uuid) as activeVisitUuid,
IF(va.value_reference = "Admitted", "true", "false") as hasBeenAdmitted
from
  visit v join person_name pn on v.patient_id = pn.person_id and pn.voided = 0 and v.voided=0
  join patient_identifier pi on v.patient_id = pi.patient_id and pi.voided=0
  join person p on p.person_id = v.patient_id  and p.voided=0
  join encounter en on en.visit_id = v.visit_id and en.voided=0
  left outer join location loc on en.location_id = loc.location_id
  join encounter_provider ep on ep.encounter_id = en.encounter_id  and ep.voided=0
  join provider pr on ep.provider_id=pr.provider_id and pr.retired=0
  join person per on pr.person_id=per.person_id and per.voided=0
  left outer join visit_attribute va on va.visit_id = v.visit_id and va.attribute_type_id = (
               select visit_attribute_type_id from visit_attribute_type where name="Admission Status"
           )
where
  v.date_stopped is null and
  loc.uuid=${location_uuid}
  order by en.encounter_datetime desc`

**Comment by brookingcharlie** [comment]
Thanks for the help - and sorry if I'm being a pain!

I'll definitely put that config into OpenMRS. But how would you recommend I approach this issue generally? As in, if it happens again, how could I find that snippet of config myself and solve the issue?

Is there a way for me to get a new openers dump, generate a dump from some scripts, etc?

(I'm asking for myself but also others trying to get traction developing with Bahmni.)

**Comment by aj-jaswanth** [comment]
You can use the fixed dbdump from here https://github.com/Bahmni/emr-functional-tests/tree/master/dbdump.

Like I said, each tab in the clinical app corresponds to a sql query in the openmrs. To get the patients to be displayed in that tab, it just fetches the key from the config (https://github.com/Bahmni/default-config/blob/b5d90ebd6fada51a4f1be08a23480d8f706d0bb0/openmrs/apps/clinical/extension.json#L109) and requests the servers. The server looks up the key in the global properties, fetches the sql query and returns the results.

If you get any future errors regarding these tabs, you can simple check if the key is present in the global properties or not. If it is not present, you can either ignore the error as it is not fatal or remove the key from your config.

You are always welcome to ask questions and clear your doubts. Community is the first priority to us. :)

**Comment by brookingcharlie** [comment]
Closing this old issue!
